services:

  mysql:
    image: mysql:8.0
    container_name: lifecare-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: lifecare_pathology
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build: .
    container_name: lifecare-backend
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lifecare_pathology
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
      TECHNICIAN_EMAIL: ${TECHNICIAN_EMAIL}
      TECHNICIAN_PASSWORD: ${TECHNICIAN_PASSWORD}

    ports:
      - "8080:8080"


  frontend:
    build: ./lifecare-pathology-frontend
    container_name: lifecare-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"


volumes:
  mysql_data: